name: push docker image to dockerhub

on:
  push:
    branches:
      - "!*"
    tags:
      - '*'

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

        - name: debug
          run: echo ${GITHUB_REF:10})

        - name: debug2
          run: echo ${{steps.vars.outputs.tag}}

        - name: Build the tagged Docker image
          run: |
            cd docker
            docker build . --file Dockerfile --tag kmille2/deezer-downloader:${{steps.vars.outputs.tag}}
        - name: Push the tagged Docker image
          run: docker push kmille2/deezer-downloader:${{steps.vars.outputs.tag}}

        - name: Build the latest Docker image
          run: |
            cd docker
            docker build . --file Dockerfile --tag kmille2/deezer-downloader:latest
        - name: Push the latest Docker image
          run: docker push kmille2/deezer-downloader:latest
